name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


defaults:
  run:
    shell: bash -l {0}


jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-11 ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    name: Python version - ${{ matrix.python-version }} - ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          condarc: |
            channels:
              - conda-forge
          environment-name: pyhtnorm-dev
          cache-environment: true
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }}
            openblas
            lapack

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run Pytest, report coverage
        env:
          BUILD_WITH_COVERAGE: true
        run: |
          cythonize pyhtnorm/*.pyx -X linetrace=True
          pip install -e .
          pytest -v --cov-branch --cov=pyhtnorm tests/ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
