# adapted from: https://github.com/pypa/cibuildwheel/tree/main/examples
name: Release

on:
  release:
    types: [ published ]

  workflow_dispatch:


defaults:
  run:
    shell: bash -l {0}


jobs:
  build_wheels_and_sdist:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-20.04, macOS-11 ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build wheels
        run: |
          python3 -m pip install --upgrade pip cibuildwheel==2.12.3
          python3 -m cibuildwheel --output-dir wheelhouse --config-file pyproject.toml

      - name: Build source distribution
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          pip install build
          python3 -m build --sdist
          mv dist/*.gz wheelhouse

      - name: Store the wheelhouse directory
        uses: actions/upload-artifact@v2
        with:
          name: wheels_and_sdist
          path: wheelhouse
          if-no-files-found: error


  upload_pypi:
    needs: [ build_wheels_and_sdist ]
    runs-on: ubuntu-20.04
    steps:
      - name: Pull built wheels and sdist
        uses: actions/download-artifact@v2
        with:
          name: wheels_and_sdist
          path: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: wheelhouse
